-- Add tour details fields to tours table
ALTER TABLE public.tours
ADD COLUMN overview_en TEXT,
ADD COLUMN overview_uz TEXT,
ADD COLUMN overview_ru TEXT,
ADD COLUMN overview_de TEXT,
ADD COLUMN itinerary_en TEXT,
ADD COLUMN itinerary_uz TEXT,
ADD COLUMN itinerary_ru TEXT,
ADD COLUMN itinerary_de TEXT,
ADD COLUMN important_info_en TEXT,
ADD COLUMN important_info_uz TEXT,
ADD COLUMN important_info_ru TEXT,
ADD COLUMN important_info_de TEXT,
ADD COLUMN location_en TEXT,
ADD COLUMN location_uz TEXT,
ADD COLUMN location_ru TEXT,
ADD COLUMN location_de TEXT,
ADD COLUMN included_en TEXT,
ADD COLUMN included_uz TEXT,
ADD COLUMN included_ru TEXT,
ADD COLUMN included_de TEXT,
ADD COLUMN not_included_en TEXT,
ADD COLUMN not_included_uz TEXT,
ADD COLUMN not_included_ru TEXT,
ADD COLUMN not_included_de TEXT;